apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: jobbplassen-frontend
  namespace: laerlinger
spec:
  ingresses:
    - https://jobbplassen-frontend.dev.nav.cloud.nais.io
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: jobbplassen-backend
          namespace: laerlinger
  env:
    - name: PORT
      value: "8080"
    - name: NODE_ENV
      value: "production"
    - name: BACKEND_URL
      value: "http://jobbplassen-backend.laerlinger.svc.cluster.local:8080"

